var bip39 = require('bip39');
var hdkey = require('hdkey');
var ethUtil = require('ethereumjs-util');
var util = require('./util');

const _default = require('./const');

var Swap = function () { }

/**
 * Generate a random Mnemonic
 * @function generateMnemonic
 * @param - 
 */
Swap.generateMnemonic = function () {
  let mnemonic = bip39.generateMnemonic();
  return mnemonic;
}

/**
 * Generate a root path
 * @function generateRootPath
 * @param networkId - Ethereum network ID, i.e, 4 for Rinkeby, 1 for Mainnet
 * @param orgnazationName - Organization name. For example: 'Kambria'
 */
Swap.generateRootPath = function (networkId, orgnazationName) {
  // Full path: m/<base>/<net>/<org>/<bnbAddressPath>
  let organization = util.stringToPath(orgnazationName);
  let path = {
    base: _default.ETH_DERIVATION_PATH,
    net: networkId,
    org: organization,
    concat: function (extraPath) {
      let dpath = util.addDPath(util.addDPath(this.base, this.net), this.org);
      if (extraPath) dpath = util.addDPath(dpath, extraPath);
      return dpath;
    }
  }
  return path;
}

/**
 * Generate a root node
 * Because this function will include private key of root node
 * So you must manually delete private key before publication.
 * You must only use it when you are in intention of 2-way swap.
 * @function generateRootNode
 * @param mnemonic - Mnemonic
 * @param passwork - Passwork. It should be null to ignore.
 * @param rootPath - rootPath object
 */
Swap.generateRootNode = function (mnemonic, passwork, rootPath) {
  console.warn(`
    You should use this function in BEP2-ERC20 swap.
    If you plan to do ERC20-BEP2 swap, please use generateSecureRootNode instead.
  `);
  let seed = bip39.mnemonicToSeedSync(mnemonic, passwork);
  let master = hdkey.fromMasterSeed(seed);
  if (typeof rootPath === 'object') rootPath = rootPath.concat();
  let root = master.derive(rootPath);
  return root;
}

/**
 * Generate a deposite node
 * Because this function will include private key of deposit node
 * So you must manually delete private key before publication.
 * You must only use it when you are in intention of 2-way swap.
 * @function generateDepositNode
 * @param root - root node
 * @param bnbAddress - BNB Address
 */
Swap.generateDepositNode = function (root, bnbAddress) {
  console.warn(`
    You should use this function in BEP2-ERC20 swap.
    If you plan to do ERC20-BEP2 swap, please use generateDepositSecureNode instead.
  `);
  let dpath = util.stringToPath(bnbAddress);
  let child = root.derive(util.addDPath('m/', dpath));
  return child;
}

/**
 * Securely generate a root node
 * We strongly recommend to use this function
 * @function generateSecureRootNode
 * @param mnemonic - Mnemonic
 * @param passwork - Passwork. It should be null to ignore.
 * @param rootPath - rootPath object
 */
Swap.generateSecureRootNode = function (mnemonic, passwork, rootPath) {
  let seed = bip39.mnemonicToSeedSync(mnemonic, passwork);
  let master = hdkey.fromMasterSeed(seed);
  if (typeof rootPath === 'object') rootPath = rootPath.concat();
  let root = master.derive(rootPath);
  delete root._privateKey;
  return { publicKey: root.publicKey, chainCode: root.chainCode };
}

/**
 * Securely generate a deposite node
 * We strongly recommend to use this function
 * @function generateSecureDepositNode
 * @param root - root node generated by generateSecureRootNode
 * @param bnbAddress - BNB Address
 */
Swap.generateSecureDepositNode = function (root, bnbAddress) {
  let bnbAddressPath = util.stringToPath(bnbAddress);
  let child = util.deriveChild(root.publicKey, root.chainCode, bnbAddressPath);
  let address = ethUtil.bufferToHex(ethUtil.pubToAddress(child.publicKey, true));
  return {
    bnbAddress: bnbAddress,
    dpath: bnbAddressPath,
    ethAddress: address
  }
}

/**
 * Validate deposit node
 * @function validateSecureDepositNode
 * @param depositNode - the deposit node returned by generateSecureDepositNode
 */
Swap.validateSecureDepositNode = function (root, depositNode) {
  let validDepositNode = Swap.generateSecureDepositNode(root, depositNode.bnbAddress);
  let keys = Object.keys(validDepositNode);
  for (let i = 0; i < keys.length; i++) {
    if (validDepositNode[keys[i]] !== depositNode[keys[i]]) return false;
  }
  return true;
}

module.exports = Swap;